// The att.com assistant panel.
//
// Rebuilt to match the real thing: a blue gradient header with the assistant's name,
// a greeting block, the "Recommended for you" list of jump-offs, timestamped turns,
// and the "some responses may be generated by AI" disclosure they carry. The
// sign-in prompt only appears when there's nobody signed in — for a member it's
// noise, and worse, it implies we don't already know who they are.
//
// The brain underneath is Agent 2 (Coverage Assistant) from src/lib/ai.ts.
import { useEffect, useRef, useState } from "react";
import { X, Send, ChevronRight, ShoppingBag, Info, Sparkles, Minus } from "lucide-react";
import { useNavigate } from "@tanstack/react-router";
import { useAuth } from "@/lib/auth";
import { assistantReply, assistantGreeting, type ChatMessage, type ChatAction } from "@/lib/ai";

const now = () =>
  new Date().toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit" }).toLowerCase();

type Turn = ChatMessage & { at: string };

/** The jump-offs att.com shows under "Recommended for you", tuned to protection. */
const RECOMMENDED_OUT = [
  { label: "What does device protection cover?", ask: "What does device protection cover?" },
  { label: "How much does it cost?", ask: "How much does it cost?" },
  { label: "Check if my device is eligible", to: "/myatt/enroll" },
  { label: "Compare protection plans", to: "/deviceflex" },
];

const RECOMMENDED_IN = [
  { label: "File a claim", to: "/myatt/claims/new" },
  { label: "What's my deductible?", ask: "What's my deductible?" },
  { label: "Open my Data Vault", to: "/myatt/vault" },
  { label: "Check my protection score", ask: "What's my protection score?" },
];

export function ChatPanel({ onClose }: { onClose: () => void }) {
  const { user, isAuthed } = useAuth();
  const navigate = useNavigate();
  const [turns, setTurns] = useState<Turn[]>([]);
  const [input, setInput] = useState("");
  const [typing, setTyping] = useState(false);
  const endRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  const started = turns.length > 0;
  const greeting = assistantGreeting({ member: user });

  useEffect(() => {
    inputRef.current?.focus();
    const k = (e: KeyboardEvent) => e.key === "Escape" && onClose();
    window.addEventListener("keydown", k);
    return () => window.removeEventListener("keydown", k);
  }, [onClose]);

  useEffect(() => {
    if (started) endRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [turns, typing, started]);

  const send = (text: string) => {
    const t = text.trim();
    if (!t || typing) return;
    setInput("");
    setTurns((m) => [...m, { role: "user", text: t, at: now() }]);
    setTyping(true);
    setTimeout(() => {
      setTurns((m) => [...m, { ...assistantReply(t, { member: user }), at: now() }]);
      setTyping(false);
    }, 550);
  };

  const go = (a: ChatAction | { to?: string; ask?: string }) => {
    if ("ask" in a && a.ask) return send(a.ask);
    if (a.to) {
      onClose();
      navigate({ to: a.to } as never);
    }
  };

  const recommended = isAuthed ? RECOMMENDED_IN : RECOMMENDED_OUT;

  return (
    <div
      role="dialog"
      aria-modal="false"
      aria-label="Chat with AT&T"
      className="fixed bottom-0 right-0 z-50 flex h-[620px] max-h-[92vh] w-[400px] max-w-full flex-col overflow-hidden rounded-t-2xl bg-white shadow-2xl sm:bottom-4 sm:right-4 sm:rounded-2xl"
    >
      {/* Header — their blue band, the assistant's name centred, close on the right. */}
      <header className="relative bg-gradient-to-r from-[#0057B8] to-[#009FDB] px-4 py-3.5 text-white">
        <p className="text-center text-lg font-extrabold tracking-[-0.02em]">Andi</p>
        <div className="absolute right-2 top-1/2 flex -translate-y-1/2 items-center gap-1">
          <button
            aria-label="Minimize chat"
            onClick={onClose}
            className="rounded-full p-1.5 hover:bg-white/15"
          >
            <Minus className="h-5 w-5" />
          </button>
          <button
            aria-label="Close chat"
            onClick={onClose}
            className="rounded-full p-1.5 hover:bg-white/15"
          >
            <X className="h-5 w-5" />
          </button>
        </div>
      </header>

      <div className="flex-1 overflow-y-auto">
        {/* Greeting card, rounded off the header the way theirs is. */}
        <div className="rounded-b-2xl bg-white px-5 pb-5 pt-5">
          {!started ? (
            <>
              <p className="flex items-center gap-2 text-xl font-extrabold tracking-[-0.02em]">
                <Sparkles className="h-5 w-5 text-[#0072B2]" />
                {isAuthed ? `Hi ${user?.firstName},` : "Hi,"}
              </p>
              <p className="att-body mt-3">{greeting.text}</p>

              {/* Only offered when there's nobody signed in. */}
              {!isAuthed && (
                <button
                  onClick={() => {
                    onClose();
                    navigate({ to: "/login", search: { returnTo: "/myatt" } });
                  }}
                  className="btn-secondary mt-4 w-full"
                >
                  Sign in
                </button>
              )}

              <label className="mt-4 block">
                <span className="sr-only">Search or ask a question</span>
                <input
                  ref={inputRef}
                  value={input}
                  onChange={(e) => setInput(e.target.value)}
                  onKeyDown={(e) => e.key === "Enter" && send(input)}
                  placeholder="Search or ask me a question"
                  className="w-full rounded-full border-2 border-[#009FDB] px-5 py-3 text-sm outline-none ring-4 ring-[#009FDB]/15 transition focus:ring-[#009FDB]/30"
                />
              </label>

              <button
                onClick={() => send("I need help choosing a protection plan")}
                className="mt-3 flex w-full items-center gap-3 rounded-xl border border-[#DCDFE3] p-3.5 text-left transition hover:border-[#00388F]"
              >
                <ShoppingBag className="h-6 w-6 shrink-0 text-[#0072B2]" />
                <span className="text-sm font-bold">
                  Need help choosing? Compare protection plans
                </span>
              </button>
            </>
          ) : (
            <div className="space-y-4">
              <p className="att-small text-center">Some responses may be generated by AI.</p>
              {turns.map((m, i) => (
                <div key={i}>
                  {m.role === "user" ? (
                    <div className="flex flex-col items-end">
                      <div className="max-w-[85%] rounded-2xl rounded-br-md bg-[#E7F5FB] px-4 py-2.5 text-sm text-[#1D2329]">
                        {m.text}
                      </div>
                      <span className="att-small mt-1">Today · {m.at}</span>
                    </div>
                  ) : (
                    <div>
                      <p className="flex items-center gap-2 text-sm font-extrabold">
                        <Sparkles className="h-4 w-4 text-[#0072B2]" />
                        Andi
                      </p>
                      <span className="att-small">Today · {m.at}</span>
                      <p className="att-body mt-2 leading-relaxed">{m.text}</p>
                      {m.actions && m.actions.length > 0 && (
                        <div className="mt-3 divide-y divide-[#DCDFE3] rounded-xl border border-[#DCDFE3]">
                          {m.actions.map((a) => (
                            <button
                              key={a.label}
                              onClick={() => go(a)}
                              className="flex w-full items-center justify-between gap-3 px-4 py-3 text-left text-sm font-bold text-[#0072B2] transition hover:bg-[#F2FAFD]"
                            >
                              {a.label}
                              <ChevronRight className="h-4 w-4 shrink-0" />
                            </button>
                          ))}
                        </div>
                      )}
                      <p className="att-small mt-2 inline-flex items-center gap-1">
                        View sources <Info className="h-3.5 w-3.5" />
                      </p>
                    </div>
                  )}
                </div>
              ))}
              {typing && (
                <div
                  className="flex w-fit items-center gap-1 rounded-2xl bg-[#F3F4F6] px-4 py-3"
                  aria-label="Andi is typing"
                >
                  {[0, 1, 2].map((i) => (
                    <span
                      key={i}
                      className="h-1.5 w-1.5 animate-bounce rounded-full bg-[#686E74]"
                      style={{ animationDelay: `${i * 120}ms` }}
                    />
                  ))}
                </div>
              )}
              <div ref={endRef} />
            </div>
          )}
        </div>

        {/* Recommended for you — their pale-blue lower shelf. */}
        {!started && (
          <div className="bg-[#E7F5FB] px-5 py-5">
            <p className="text-base font-extrabold tracking-[-0.02em]">Recommended for you</p>
            <div className="mt-3 divide-y divide-[#C9E6F5] overflow-hidden rounded-xl bg-white">
              {recommended.map((r) => (
                <button
                  key={r.label}
                  onClick={() => go(r)}
                  className="flex w-full items-center justify-between gap-3 px-4 py-3.5 text-left text-sm font-bold transition hover:bg-[#F2FAFD]"
                >
                  {r.label}
                  <ChevronRight className="h-4 w-4 shrink-0 text-[#0072B2]" />
                </button>
              ))}
            </div>
          </div>
        )}
      </div>

      {/* Composer — only once a conversation is running; before that the hero input has it. */}
      {started && (
        <form
          onSubmit={(e) => {
            e.preventDefault();
            send(input);
          }}
          className="flex items-center gap-2 border-t border-[#DCDFE3] bg-white p-3"
        >
          <input
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder="Reply or ask me a question"
            aria-label="Reply or ask a question"
            className="flex-1 rounded-full border border-[#DCDFE3] px-4 py-2.5 text-sm outline-none transition focus:border-[#00388F]"
          />
          <button
            type="submit"
            aria-label="Send message"
            disabled={!input.trim()}
            className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-[#00388F] text-white transition hover:bg-[#0057B8] disabled:opacity-40"
          >
            <Send className="h-4 w-4" />
          </button>
        </form>
      )}
    </div>
  );
}
